= HackX

Extensions to Hack

== Halt

The Halt hack instruction will cause the CPU's PC to stop incrementing.
This is achieved by sending an instruction that both reads from and writes to memory.
While there are numerous commands that have this effect, canonically it is the C command to read from M and write 0 to AMD, with an unconditional jump.
The PC can be re-enabled by sending the Reset signal, which will clear the PC to 0x0000 and put it back in counting mode.
There is no mechanism to send the reset signal via software.

`1111 1111 1111 1111`

The Hack VM has the instruction `halt`.

== NOOP, noop

A shorthand for A0, the A instruction which loads 0 into the A register and does nothing else.
Exists to allow the asm to fill in areas of the output assembly as needed.

`0000 0000 0000 0000`

The Hack VM has the instruction `noop`.

== ALUX - Extended Arithmetic

`1 1x m cccccc ddd jjj`

In a hack c instruction, the second bit becomes an "Arithmetic" instruction.
When set to 1, the machine will perform ALU arithmetic.
The third bit will choose between standard (when 1) and eXtended (when 0).
The ALU will read from memory if the m bit is set; will use the c bits to control the logic, and d bits to control where to store results.
In standard mode, the j bits control the jump destination.
In extended mode, the j bits select additional arithmetic operations.

jjj | Operation                 | ASM Cmp | Hack VM
----|---------------------------|---------|---------
000 | left shift                | SHL {n} | shift-left {n}
001 | right shift               | SHR {n} | shift-right {n}
010 | integer multiplication    | MUL     | mul
011 | integer division          | DIV     | div
100 | floating point add        | FADD    | fadd 
101 | floating point subtract   | FSUB    | fsub
110 | floating point multiply   | FMUL    | fmul
111 | floating point divide     | FDIV    | fdiv

Shift uses the lowest 4 c-bits to determine the amount of places to shift.
Left shift is 0 fill, right shift is signed fill, to keep with the multiplication/division pattern.
When an immediate shift amount is provided to the VM, a single value is popped and pushed.

ALUX has an expanded out bit buffer.
The ALU out buffer can be read at 0xFFFF

Bit | OB | Meaning      |  Comment
----|----|--------------|----------------
 15 | ng | Negative     | Based on sign bit of result
 14 | zr | Zero         | All result bits are 0
 13 | ov | Overflow     | Overflow, if exponent positive, or Underflow, if exponent negative
 12 |nan | Not A Number | Result (or intermediates) is Not A Number
 11 |inf | Infinity     | Positive or negative based on ng
0-10|N/A | None         | Reserved for future use

== Interrupts

The CPU can handle interrupts one level deep.
If it is handling an interrupt, any hardware or software is ignored.

=== Interrupt Instructions

Instruction             | Operation
------------------------|----------------------------------------------------
`            1aaa a000` | Out of band, put the CPU in interrupt mode, and jump to a 
`1 0x 0 ???? 1aaa a000` | Put CPU in interrupts mode, and jump to a
`1 01 0 ???? ???? ????` | Restore CPU to normal mode, and jump to restored PC  

The Computer adds an 8-bit interrupt bus, along with a software interrupt signal.
On receiving a 1 in the interrupt bus, or the software interrupt instruction, the CPU caches inM, A, D, the PC, the ALU status bus.
The CPU then marks as in interrupt state. If any interrupt commands arrive while in the interrupt, they are ignored.
The CPU then jumps to the address specified by the interrupt.
The last three bits of the interrupt must be 0, leaving 8 instructions for machine start:

----
@256
D=A
@SP
M=D
@Sys.init
0;JMP
NOOP
NOOP
----

=== Interrupt processing

Peripherals have mapped regions.

Four IRQ regions:

* IRQ1 Keyboard
* IRQ2 Mouse
* IRQ3 Video memory
* IRQ4 Hard drive
* IRQ5 Network

IRQ pointers are the first 4 static variables.
IRQ pointers take two bytes.
The first byte is managed by the system, and is the memory offset for the IRQ device.
The second byte is set by the device, for reads, or the software, for writes, and includes the number of bytes modified.

IRQ command: [Read|Write] IRQ# LENGTH

Write LENGTH bytes from MEM[OFFSET] into the device at IRQ#
WRITE IRQ# OFFSET LENGTH

Read LENGTH bytes from IRQ device into MEM starting at [OFFSET]

== Prog

= JackX

== JackX VM additions

Add bitwise rotations: SHL, SHR [x][y] => [x << y]
Add binary f instructions: `addf`, `subf`, `mulf`, `divf`

== Jack OS additions

=== Process

Process handling

=== Screen

