name: Bug Report
description: File a bug report
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report on the NAND2Tetris Web IDE or VSCode Extension
  - type: dropdown
    id: program
    attributes:
      label: Tool
      description: Select the tool about which you wish to report the bug / issue
      options:
        - Hardware Simulator
        - CPU Emulator
        - Assembler
        - VM Emulator
        - Jack Compiler
        - General
  - type: dropdown
    id: interface
    attributes:
      label: Interface
      description: Which NAND2Tetris interface were you using?
      options:
        - Website (https://nand2tetris.github.io/web-ide)
        - VSCode Extension (coming soon, or manually installed)
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: What else, if anything, would you like to share with us?
      placeholder: "Tell us anything!"
    validations:
      required: false
  - type: checkboxes
    id: self-fix
    attributes:
      label: Do you want to try to fix this bug?
      description: The IDE is written in TypeScript, and includes React components. Do you want to try to fix the bug yourself (optional question)? If so, you can fork the repo, try to make the fix, and submit a PR.
      options:
        - label: I want to try to add this feature!
          required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/nand2tetris/web-ide/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
